# 전역 설정
global:
  environment: default
  namespace: model-serving

# 이미지 설정
image:
  repository: docker.io/jongsue/model-serving
  tag: latest
  pullPolicy: IfNotPresent

# API 서버 설정
api:
  name: api
  replicas: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
  resources:
    requests:
      memory: "512Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

# Celery 워커 설정
worker:
  name: worker
  replicas: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  gpu:
    enabled: false
    count: 1

# Redis 설정
redis:
  name: redis
  image:
    repository: redis
    tag: "6"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  service:
    port: 6379

# PostgreSQL 설정
postgres:
  name: postgres
  image:
    repository: postgres
    tag: "13"
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  storage:
    size: 10Gi
    class: standard
  service:
    port: 5432
  credentials:
    user: user
    password: password
    database: modeldb

# 초기화 작업 설정
initJob:
  enabled: true
  backoffLimit: 4

# 인그레스 설정
ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  host: model-api.local
  tls:
    enabled: false
    secretName: model-api-tls