apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ include "model-serving.namespace" . }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.credentials.database }}
  POSTGRES_HOST: {{ .Values.postgres.name }}
  POSTGRES_PORT: "{{ .Values.postgres.service.port }}"
  REDIS_HOST: {{ .Values.redis.name }}
  REDIS_PORT: "{{ .Values.redis.service.port }}"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  ENVIRONMENT: {{ .Values.global.environment }}