{{- if .Values.initJob.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  namespace: {{ include "model-serving.namespace" . }}
  labels:
    {{- include "model-serving.labels" . | nindent 4 }}
    app: init-db
spec:
  backoffLimit: {{ .Values.initJob.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "model-serving.labels" . | nindent 8 }}
        app: init-db
    spec:
      containers:
      - name: init-db
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python", "init_db.py"]
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: POSTGRES_PORT
      restartPolicy: Never
{{- end }}